# 服务器端口 (Server port)
server.port=9198

# HLS 静态内容服务 (Static content serving for HLS)
# classpath:/static/ 是指 src/main/resources/static 目录
# file:./hls-output/ 是指应用运行目录下的 hls-output 文件夹
spring.web.resources.static-locations=classpath:/static/,file:./hls-output/

# 定义 FFmpeg 输出 HLS 文件的目录 (Define a directory for HLS output FFmpeg will write here)
ffmpeg.output.directory=./hls-output/
