# Server port
server.port=8080

# Static content serving for HLS
spring.web.resources.static-locations=classpath:/static/,file:./hls-output/
# Define a directory for HLS output (FFmpeg will write here)
ffmpeg.output.directory=./hls-output/
